### ISSUE TITLE
No module named 'object_detection'

### ISSUE THREAD

**Issue by orcund** [mesutpiskin/id-card-detector#10]
Traceback (most recent call last):
  File "id_card_detection_image.py", line 13, in <module>
    from utils import label_map_util
  File "C:\Users\Orcun\id-card-detector-master\utils\label_map_util.py", line 21, in <module>
    from object_detection.protos import string_int_label_map_pb2
ModuleNotFoundError: No module named 'object_detection'

**Comment by mesutpiskin** [comment]
Hi,
You need to Tensorflow models
https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/installation.md

Download tensorflow models and go to  \model master\models-master\research open cmd or terminal in this path and type `python setup.py install` or `python3 setup.py install`


https://github.com/tensorflow/models/issues/2031

**Comment by orcund** [comment]
> Hi,
> You need to Tensorflow models
> https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/installation.md
> 
> Download tensorflow models and go to \model master\models-master\research open cmd or terminal in this path and type `python setup.py install` or `python3 setup.py install`
> 
> [tensorflow/models#2031](https://github.com/tensorflow/models/issues/2031)

Thanks, I just used your inference graph on opencv. 

##Eski ve yeni kimliklerin ikisiyle de egitmeniz cok iyi olmus :D

**Comment by Jayanth1812** [comment]
I am getting the following errors.. when I run the main training program..
(tensorflow) C:\tensorflow\models\research\object_detection>python train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/faster_rcnn_inception_v2_pets.config
Traceback (most recent call last):
File "train.py", line 54, in
from object_detection.builders import model_builder
File "C:\tensorflow\models\research\object_detection\builders\model_builder.py", line 20, in
from object_detection.builders import anchor_generator_builder
File "C:\tensorflow\models\research\object_detection\builders\anchor_generator_builder.py", line 23, in
from object_detection.anchor_generators import flexible_grid_anchor_generator
ModuleNotFoundError: No module named 'object_detection.anchor_generators'
