### ISSUE TITLE
Prediction takes 6-7 seconds per image

### ISSUE THREAD

**Issue by jgtjerry** [mesutpiskin/id-card-detector#14]
Hello,

I have been testing the model on some of the images. I am using mac OS 

This prediction step takes 6-7 seconds per image:

(boxes, scores, classes, num) = sess.run([detection_boxes, detection_scores, detection_classes, num_detections],feed_dict={image_tensor: image_expanded})

Is this normal? If not, how can I speed it up?

Thanks

**Comment by mesutpiskin** [comment]
Hi jgtjerry,

Sorry, I don't have a suggestion but you can look at this link.
https://www.dlology.com/blog/how-to-run-tensorflow-object-detection-model-faster-with-intel-graphics/
