### ISSUE TITLE
new id card

### ISSUE THREAD

**Issue by mobileonekh** [mesutpiskin/id-card-detector#2]
Thanks for sharing..

I want to identify my country ID card. Can you elaborate on how to train new card type?
And is it possible to OCR different language than English?

Thanks;

**Comment by mesutpiskin** [comment]
Hi, this can recognize all ID cards. If you want to retrain, you can create a dataset and apply the following example. 

https://github.com/EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10
