### ISSUE TITLE
Gazeml nor object-recognition could not be found or installed

### ISSUE THREAD

**Issue by prodoxx** [mesutpiskin/id-card-detector#20]
I got this error when installing the requirements:

```
 Could not find a version that satisfies the requirement gazeml==0.1 (from -r requirements.txt (line 38)) (from versions: )
No matching distribution found for gazeml==0.1 (from -r requirements.txt (line 38))
```

...and it didn't continue installing the rest. Any suggestions?

Also, it couldn't install object-recognition: 

```
 Could not find a version that satisfies the requirement object-detection==0.1 (from -r requirements.txt (line 82)) (from versions: )
No matching distribution found for object-detection==0.1 (from -r requirements.txt (line 82))
```

**Comment by Sanix-Darker** [comment]
Use this :
```
pip3 install object-detection-0.1
```
i fix my issue like that !

**Comment by dogcalas** [comment]
You should download the requirement directly from github repo. Replace in requirements.txt
```gazeml==0.1```
BY
```git+git://github.com/swook/GazeML@master```

**Comment by mesutpiskin** [comment]
Can you contributing to this project

**Comment by mesutpiskin** [comment]
> You should download the requirement directly from github repo. Replace in requirements.txt
> `gazeml==0.1`
> BY
> `git+git://github.com/swook/GazeML@master`

Can you contributing to this project
