### ISSUE TITLE
NameError: name 'image_path' is not defined in id_card_detection_image.py

### ISSUE THREAD

**Issue by jeffrey008** [mesutpiskin/id-card-detector#27]
I got this error when running `py id_card_detection_image.py`
```
Traceback (most recent call last):
  File "id_card_detection_image.py", line 105, in <module>
    im = Image.open(image_path)
NameError: name 'image_path' is not defined
```
I also notice similar error in my IDE PyCharm, the red underlines are undefined variable.
![image](https://user-images.githubusercontent.com/11265387/83212991-8ad99080-a193-11ea-8101-9765ca3a2bbb.png)

Am I missing something? Thanks!

**Comment by mesutpiskin** [comment]
image_path and output_path is your physical file path, please define these variables, for example 
```
image_path = "C:\Users\ali-veli-user\Desktop\my_input_photos.jpg"
output_path= "C:\Users\ali-veli-user\Desktop\detected_id.jpg"
```
