### ISSUE TITLE
Training Module 

### ISSUE THREAD

**Issue by kundanSingh11** [mesutpiskin/id-card-detector#35]
How to train the model i have enough data can you share the training code for the model

**Comment by anhcongduc** [comment]
hello sir can you give me your data.
my email dinhhungdeptraiso1traidat@gmail.com
thanks you

**Comment by mesutpiskin** [comment]
i cannot share the data set here because it contains personal information.

https://github.com/mesutpiskin/id-card-detector/issues/31

**Comment by kundanSingh11** [comment]
don't need data need training code
