### ISSUE TITLE
crop & save image

### ISSUE THREAD

**Issue by AhmadAlhati** [mesutpiskin/id-card-detector#9]
After running (id_card_detection_image.py) file, can not find the saved cropped image.

**Comment by mesutpiskin** [comment]
Can you share the error results? 

`IMAGE_NAME = 'test images / image1.png'. `

# you must change it

**Comment by AhmadAlhati** [comment]
yes i changed IMAGE_NAME to the image i want to process
and have no error with running the full project
i just read the readme file, and i expect the output to be an card image.
after crop and skewing the original image.

but the output only give me an image with green rectangle around the detected card.
NO cropping or skewing..
that's what am asking about 
how to use your output to perform such an operation?

**Comment by mesutpiskin** [comment]
Sory for that Ahmet,  somehow i forgot. You can this with crop_to_bounding_box https://www.tensorflow.org/api_docs/python/tf/image/crop_to_bounding_box

**Comment by Sanix-Darker** [comment]
Hey @mesutpiskin , i can help for this, this is how you crop the image of the id-card in the image:
 
1- Go in `utils/visualisation_utils` and update the method, principally the return of the method like this : 
```python
def visualize_boxes_and_labels_on_image_array(
        image,
        boxes,
        classes,
        scores,
        category_index,
        instance_masks=None,
        instance_boundaries=None,
        keypoints=None,
        use_normalized_coordinates=False,
        max_boxes_to_draw=20,
        min_score_thresh=.5,
        agnostic_mode=False,
        line_thickness=4,
        groundtruth_box_visualization_color='black',
        skip_scores=False,
        skip_labels=False):
...

........

return image, [ymin, xmin, ymax, xmax]
```

2- Then In your main code, you can call that method like this call ``

```python
   # using Image lib
   import Image

    # Draw the results of the detection (aka 'visulaize the results')
    image, array_coord = vis_util.visualize_boxes_and_labels_on_image_array(
        image,
        np.squeeze(boxes),
        np.squeeze(classes).astype(np.int32),
        np.squeeze(scores),
        category_index,
        use_normalized_coordinates=True,
        line_thickness=3,
        min_score_thresh=0.60)

   # Getting all x,y,
    ymin, xmin, ymax, xmax = array_coord

    shape = np.shape(image)
    im_width, im_height = shape[1], shape[0]
    (left, right, top, bottom) = (xmin * im_width, xmax * im_width, ymin * im_height, ymax * im_height)

    # Using Image to crop and save the extracted image
    # Open the original image
    im = Image.open(image_path)
    
    # Crop it with coordinates
    im.crop((left, top, right, bottom)).save(output_path, quality=95)
```

**Comment by mesutpiskin** [comment]
> Hey @mesutpiskin , i can help for this, this is how you crop the image of the id-card in the image:
> 
> 1- Go in `utils/visualisation_utils` and update the method, principally the return of the method like this :
> 
> ```python
> def visualize_boxes_and_labels_on_image_array(
>         image,
>         boxes,
>         classes,
>         scores,
>         category_index,
>         instance_masks=None,
>         instance_boundaries=None,
>         keypoints=None,
>         use_normalized_coordinates=False,
>         max_boxes_to_draw=20,
>         min_score_thresh=.5,
>         agnostic_mode=False,
>         line_thickness=4,
>         groundtruth_box_visualization_color='black',
>         skip_scores=False,
>         skip_labels=False):
> ...
> 
> ........
> 
> return image, [ymin, xmin, ymax, xmax]
> ```
> 
> 2- Then In your main code, you can call that method like this call ``
> 
> ```python
>    # using Image lib
>    import Image
>    .........
>    .......
>    ............
>     # Draw the results of the detection (aka 'visulaize the results')
>     image, array_coord = vis_util.visualize_boxes_and_labels_on_image_array(
>         image,
>         np.squeeze(boxes),
>         np.squeeze(classes).astype(np.int32),
>         np.squeeze(scores),
>         category_index,
>         use_normalized_coordinates=True,
>         line_thickness=3,
>         min_score_thresh=0.60)
> 
>    # Getting all x,y,
>     ymin, xmin, ymax, xmax = array_coord
> 
>     shape = np.shape(image)
>     im_width, im_height = shape[1], shape[0]
>     (left, right, top, bottom) = (xmin * im_width, xmax * im_width, ymin * im_height, ymax * im_height)
> 
>     # Using Image to crop and save the extracted image
>     # Open the original image
>     im = Image.open(image_path)
>     
>     # Crop it with coordinates
>     im.crop((left, top, right, bottom)).save(output_path, quality=95)
> ```

Can you contributing to this project

**Comment by Sanix-Darker** [comment]
Of course @mesutpiskin, i will do a PR !

**Comment by mesutpiskin** [comment]
@Sanix-Darker Thanks for that , marged https://github.com/mesutpiskin/id-card-detector/pull/22
